// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class ImageGallerySaverApiPigeonCodecReader: FlutterStandardReader {
}

private class ImageGallerySaverApiPigeonCodecWriter: FlutterStandardWriter {
}

private class ImageGallerySaverApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ImageGallerySaverApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ImageGallerySaverApiPigeonCodecWriter(data: data)
  }
}

class ImageGallerySaverApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ImageGallerySaverApiPigeonCodec(readerWriter: ImageGallerySaverApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ImageGallerySaverApi {
  /// Save image to gallery
  func saveImage(imageBytes: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  func saveFile(filePath: String, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ImageGallerySaverApiSetup {
  static var codec: FlutterStandardMessageCodec { ImageGallerySaverApiPigeonCodec.shared }
  /// Sets up an instance of `ImageGallerySaverApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ImageGallerySaverApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Save image to gallery
    let saveImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_image_gallery_saver.ImageGallerySaverApi.saveImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let imageBytesArg = args[0] as! FlutterStandardTypedData
        api.saveImage(imageBytes: imageBytesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveImageChannel.setMessageHandler(nil)
    }
    let saveFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_image_gallery_saver.ImageGallerySaverApi.saveFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        api.saveFile(filePath: filePathArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveFileChannel.setMessageHandler(nil)
    }
  }
}
